<?php /*

[ApiProvider]
ProviderClass[contentstaging]=eZContentStagingRestApiProvider

[RouteSettings]
# no oauth auth: client does not support it (yet)
SkipFilter[]=eZContentStagingRestContentController_*
SkipFilter[]=eZContentStagingRestLocationController_*

[RequestFilters]
Filters[]=eZContentStagingAutoAuthFilter
Filters[]=eZContentStagingJsonRequestFilter


[eZContentStagingRestContentController_create_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestContentController_update_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestContentController_remove_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestContentController_addLocation_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestContentController_updateSection_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestContentController_removeTranslation_CacheSettings]
ApplicationCache=disabled

[eZContentStagingRestLocationController_hideUnhide_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestLocationController_update_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestLocationController_move_CacheSettings]
ApplicationCache=disabled
[eZContentStagingRestContentController_remove_CacheSettings]
ApplicationCache=disabled

*/ ?>
