<?php /*

[ApiProvider]
ProviderClass[contentstaging]=contentStagingRestApiProvider

[RouteSettings]
# Skip (auth) filter for every action in 'myController' which is of API version 1
SkipFilter[]=contentStagingRestContentController_*

[RequestFilters]
Filters[]=contentStagingAutoAuthFilter

[contentStagingRestContentController_remove_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_addLocation_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_hideUnhide_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_move_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_removeLocation_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_removeTranslation_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_updateSection_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_updateSort_CacheSettings]
ApplicationCache=disabled

[contentStagingRestContentController_updateAlwaysAvailable_CacheSettings]
ApplicationCache=disabled

*/ ?>
