<?php /*

[ApiProvider]
ProviderClass[contentstaging]=contentStagingRestApiProvider

[RouteSettings]
# no oauth auth: client does not support it (yet)
SkipFilter[]=contentStagingRestContentController_*
SkipFilter[]=contentStagingRestLocationController_*

[RequestFilters]
Filters[]=contentStagingAutoAuthFilter
Filters[]=contentStagingJsonRequestFilter


[contentStagingRestContentController_create_CacheSettings]
ApplicationCache=disabled
[contentStagingRestContentController_update_CacheSettings]
ApplicationCache=disabled
[contentStagingRestContentController_remove_CacheSettings]
ApplicationCache=disabled
[contentStagingRestContentController_addLocation_CacheSettings]
ApplicationCache=disabled
[contentStagingRestContentController_updateSection_CacheSettings]
ApplicationCache=disabled
[contentStagingRestContentController_removeTranslation_CacheSettings]
ApplicationCache=disabled

[contentStagingRestLocationController_hideUnhide_CacheSettings]
ApplicationCache=disabled
[contentStagingRestLocationController_update_CacheSettings]
ApplicationCache=disabled
[contentStagingRestLocationController_move_CacheSettings]
ApplicationCache=disabled
[contentStagingRestContentController_remove_CacheSettings]
ApplicationCache=disabled




*/ ?>
