<?php
/**
 * An eZ REST prerouting filter: it just turns off echoing to screen of php warnings
 * which are generated by code executed as rest service when debugOutput is on
 * and ezdebug::writedebug is called.
 * This happens eg. if the eZFormToken extension is activated, and since it happens
 * in the auth filtering phase, we need to prevent it via a prerouting filter
 *
 * @package ezcontentstaging
 *
 * @version $Id$;
 *
 * @author
 * @copyright
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 */

class eZContentStagingPreventWarningsFilter implements ezpRestPreRoutingFilterInterface
{
    public function __construct( ezcMvcRequest $request )
    {

    }

    public function filter()
    {
        error_reporting( error_reporting() & ~E_USER_NOTICE );
    }

}

?>